import random

def lost_activity_check() -> str :
    lost_activities = [
        'ate too much',
        'hungry',
        'lost an argument',
        'got roasted',
        'triggered anti-spam system',
        'cold',
        'bitten by a cat',
        'lost an argument to themselves',
        'used MEE6',
        'suck at being online',
        'played too much golf',
        'uno reverse',
        'cuz why not?',
        'too much normal brain cells',
        'Normal cells decayed (refer LDR)',
        'existing',
        'got nuked',
        'pinged too much',
        'replied too fast',
        'offline',
        'it looks good on you',
        'got grounded',
        'math',
        'spilled tea',
        'embed fail',
        'L grammer',
        'got bonked, hard',
        'got bonked',
        'battery low',
        '"Cuz I feel like it"',
        'mini-modding',
        'share chocolate condition was not satisfied',
        '"Git gud"',
        'your doctor prescribed this',
        'no nitro?',
        'L',
        'no friends',
        'got rickrolled',
        'failed to rickroll',
        'acted too smart',
        'failure',
        'emotional damage probably',
        "'o.o you really don't know?'",
        'watched the wrong anime',
        'simping',
        'suck at chess',
        "don't know the theory of brain cells",
        'fell off the chair',
        'got rekt by exams',
        'sleep deprived',
        'spammed',
        'born failure',
        '69',
        'slept too much',
        'you have a crush on someone',
        'were idle for too long',
        'room temp iq (understatement)',
        'Attitude',
        'Ratio',
        'Touched grass',
        'cringe',
        '"get real"',
        'your problem',
        '"it was some really dumb reason, so I forgot to record it"',
        'not funny',
        '"ok and?"',
        "'it's you're not your'",
        'jealous',
        'cancelled',
        'ignored',
        '"error 069, too dumb to record"',
        'Windows restarted',
        'lack a life',
        '"cuz I felt like it"',
        'not enough corrupt cells',
        'Forgot to call',
        'has too many pings',
        'procrastination',
        'too busy',
        'too free',
        'feeling sick',
        'Loves history',
        'killed a bug (an actual one)',
        'used cellculator after a long time',
        'sad single',
        '"Learn to read"',
        # new
        "Karma",
        "Absolute piece of trash"
        "Uses twitter",
        "Supports new username system",
        "Scammed",
        "your dad gave you an earful for something you didn't do",
        "Rest in Pizza",
        "Got spooked by a cat",
        "Dropped their stuff",
        "Got the date wrong!",
        "Can't read a clock",
        "'wet'",
        "Burned the cookies!!!",
        "sad",
        "A little too confident"

    ]
    
    return random.choices(lost_activities)


def gain_activity_check() -> str :
    r = random.randint(4,20)
    gain_activities =[
        'Stonks?',
        'nice shoes',
        'online status',
        'reflected a roast with no effort',
        f'the {r}th message you sent today',
        'you are funny',
        'happy, single',
        'mom?',
        'read all pings',
        'that no u moment',
        'slept 8 hours',
        'discord dark theme user',
        'probably a mistake by me, sorry',
        'read about Cellculator',
        'won in something, not that big of a deal',
        'gravity',
        'rickrolled someone successfully.. yea no, but nice try',
        '"I am feeling generous today"',
        'homework complete',
        'knows the theory of braincells well',
        'uses cellculator frequently',
        'W',
        'Luck by chance',
        'the weather is sure nice',
        'decent battery',
        'un-hungry',
        'knows about hypesquads',
        'had a great breakfast',
        'hydrated',
        'ventilated',
        'avoided the nuke',
        "didn't touch grass",
        'dark theme user',
        "agrees to bane Newton's existence",
        'corrupt cells reverted to normal (refer LDR)',
        '"Oh, my bad you were not supposed to gain any"',
        'checked on friends',
        "didn't ignore people",
        'used logic',
        "Cellculator's pity",
        'you finally took a bath today',
        'homework completed',
        'woke up early',
        'slept early',
        'have thier windows open',
        "It says Cat's blessing?!?",
        'decent at chess',
        'smart play',
        'uno reverse blocked',
        'has a life now',
        'got away with a lie',
        'actually helped for once',
        'bullying bullies',
        '(redacted)',
        'sent help',
        'got good marks',
        'ba dum tss!',
        '"Wrong user, my bad"',
        'made people fall of the chair',
        'no regrets, for today',
        'good at math',
        'active',
        "hasn't ghosted anyone today",
        'secretly joined the chaos',
        "doesn't actually simps",
        'worked hard',
        'knows grammer',
        'thinking about their one and only',
        '+respect',
        'dealt great emotional damage',
        'sympathy',
        'spam emojis is False',
        'used a great GIF',
        'appreciates cellculator',
        'no nitro flex was observed today',
        'spent time with their family',
        'petted some fluflly creatures',
        'knows another langauge',
        'no detention today',
        'thinking of doing a voice reveal',
        'no CAPS',
        'good at singing',
        'human confirmed',
        'cleaned their table',
        'read a book',
        'wrote a poem, now you gotta share it',
        'GG!',
        'you are worthy',
        'made your bed',
        'went on a date',
        'VOTED CELLCULATOR ON top.gg?!?!',
        'pure chaos',
        'lurking the right way',
        'these are extras',
        'was cool for 69 seconds',
        'draws well',
        'sweet :)',
        'Actually turned the fan off',
        'smiling for no reason in the morning',
        'just kidding, this increment is purely fake.',
        'Piano Lessons',
        'Tidy room',
        'nice socks',
        'knows how to cook',
        'SIKE!',
        # new
        'Read a book',
        'Got praised by mom',
        'Stupidly high Luck',
        'Promotes choas',
        'Emoji master',
        'Sent an amazing GIF',
        'Exhaled CO2',
        'For simply existing',
        'Looking forward to their marriage',
        'HACKS?!?!'
    ]

    return random.choices(gain_activities)


